### ISSUE TITLE
Небезопасная вставка данных

### ISSUE THREAD

**Issue by tm-minty** [Ganza6/csv-to-database#2]
https://github.com/Ganza6/csv-to-database/blob/7855c9ad72078332b7dcd4c7d857ca21fa6af5bf/db.py#L37
Так делать не стоит, это небезопасно. Так же не нужно изменять входные данные (кавычки).

**Comment by Ganza6** [comment]
Исправил, теперь я загружаю данные в базу более безопасно и не изменяю входные данные.
